import type { CloudInitArgs } from '../types.js'

export const buildCloudInit = (args: CloudInitArgs): string => {
  const tsAuthKey = args.tsAuthKey
  const host = args.host
  const user = args.user ?? 'dev'
  const yaml = [
    '#cloud-config',
    'package_update: true',
    'package_upgrade: true',
    'users:',
    `  - name: ${user}`,
    '    groups: sudo',
    '    shell: /bin/bash',
    '    sudo: "ALL=(ALL) NOPASSWD:ALL"',
    '    lock_passwd: true',
    '    passwd: "*"',
    'runcmd:',
    '  - curl -fsSL https://tailscale.com/install.sh | sh',
    `  - tailscale up --auth-key=${tsAuthKey} --ssh --hostname=${host}`,
    '  - |',
    '    if command -v apt-get >/dev/null 2>&1; then',
    '      apt-get update && apt-get install -y ufw git tmux build-essential',
    '    elif command -v dnf >/dev/null 2>&1; then',
    '      dnf install -y ufw git tmux make gcc',
    '    elif command -v yum >/dev/null 2>&1; then',
    '      yum install -y ufw git tmux make gcc',
    '    fi',
    '  - systemctl stop ssh 2>/dev/null || systemctl stop sshd 2>/dev/null || true',
    '  - systemctl disable ssh 2>/dev/null || systemctl disable sshd 2>/dev/null || true',
    '  - systemctl mask ssh 2>/dev/null || systemctl mask sshd 2>/dev/null || true',
    '  - ufw --force disable',
    '  - ufw --force reset',
    '  - ufw default deny incoming',
    '  - ufw default allow outgoing',
    '  - ufw default deny routed',
    '  - ufw allow in on tailscale0',
    '  - ufw --force enable',
    '  - ufw delete allow 22/tcp 2>/dev/null || true',
    '  - ufw delete allow 22/udp 2>/dev/null || true',
    '  - ufw delete allow ssh 2>/dev/null || true',
    '  - ufw delete allow OpenSSH 2>/dev/null || true',
    '  - ufw delete allow 22 2>/dev/null || true',
    '  - ufw delete allow from any to any port 22 2>/dev/null || true',
    '  - ufw deny 22/tcp',
    '  - ufw deny 22/udp',
    '  - ufw reload',
    '  - |',
    '    cat > /usr/local/bin/lockdown-ssh.sh << "EOF"',
    '    #!/bin/bash',
    '    ufw delete allow 22/tcp 2>/dev/null || true',
    '    ufw delete allow 22/udp 2>/dev/null || true',
    '    ufw delete allow ssh 2>/dev/null || true',
    '    ufw delete allow OpenSSH 2>/dev/null || true',
    '    ufw deny 22/tcp',
    '    ufw deny 22/udp',
    '    ufw reload',
    '    systemctl mask ssh 2>/dev/null || true',
    '    systemctl mask sshd 2>/dev/null || true',
    '    EOF',
    '  - chmod +x /usr/local/bin/lockdown-ssh.sh',
    '  - echo "@reboot root /usr/local/bin/lockdown-ssh.sh" >> /etc/crontab',
    '  - sleep 5 && /usr/local/bin/lockdown-ssh.sh &'
  ].join('\n')
  return yaml
}