name = "ajcwebdev-marko"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-06"

[site]
  bucket = "./dist"
  entry-point = ""
  include = ["assets/**"]

[build]
  command = "yarn build"

[build.upload]
  format = "service-worker"